Name    = "Ehtisham Ahmad"

email   = "ehtishamahmed10@gmail.com"

--------
## Assignment:
--------

### n_estimator:
- This is the number of trees you want to build before taking the maximum voting or averages of predictions.
- Higher number of trees give you better performance but makes your code slower. 
- You should choose as high value as your processor can handle because this makes your predictions stronger and more stable.
- The default value for this parameter is 10, which means that 10 different decision trees will be constructed in the random forest.
- The best number of trees was n_estimators=250 becuase it has less log loss.
- We have taken its value as 100 in our practice because it makes a good and reliable number of trees for average performing systems(PC).

--------------

### Random Forest Regressor:

In [39]:
# import sample data
import pandas as pd
import numpy as np
import seaborn as sns
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
X = df.iloc[:,:-2]
y = df.iloc[:,-2:-1]

In [41]:
X.head()

sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4

In [42]:
y.head()

petal_width
0          0.2
1          0.2
2          0.2
3          0.2
4          0.2

In [43]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100)
model.fit(X,y)
model.predict([[10,4,2]])

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_9956/3427943330.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X,y)
C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.333])

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=0)
predictions = model.predict(X_test)
predictions

array([2.236     , 1.101     , 0.216     , 1.893     , 0.215     ,
       2.40273333, 0.271     , 1.457     , 1.509     , 1.293     ,
       1.57908333, 1.499     , 1.276     , 1.439     , 1.371     ,
       0.14243333, 1.461     , 1.252     , 0.20653333, 0.329     ,
       1.982     , 1.477     , 0.219     , 0.19536667, 1.721     ,
       0.205     , 0.369     , 1.311     , 1.004     , 0.364     ])

In [45]:
# score
score= model.score(X_test, y_test)
print('Score : ',score)

Score :  0.9901120795628997


In [46]:
## Checking the mean squared error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, predictions)

0.0047471906018518506

In [47]:
# evaluation through r2 score
from sklearn.metrics import r2_score
score1=r2_score(y_test,predictions)
print('R2 Score : ', score1)

R2 Score :  0.9901120795628997


--------------------
## Performing on Another data:
-------------

In [49]:
df= pd.read_csv('mldata.csv')
df.head()

age   height  weight gender likeness
0   27  170.688    76.0   Male  Biryani
1   41  165.000    70.0   Male  Biryani
2   29  171.000    80.0   Male  Biryani
3   27  173.000   102.0   Male  Biryani
4   29  164.000    67.0   Male  Biryani

In [51]:
X=df[['age','height']]
y=df['weight']

In [52]:
X.head()

age   height
0   27  170.688
1   41  165.000
2   29  171.000
3   27  173.000
4   29  164.000

In [54]:
y.head()

0     76.0
1     70.0
2     80.0
3    102.0
4     67.0
Name: weight, dtype: float64

In [57]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=80)
model.fit(X,y)
model.predict([[27,170]])

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([73.44392361])

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=0)
predictions = model.predict(X_test)
predictions

array([ 77.973125  ,  51.74875   ,  74.740625  ,  67.11541667,
        86.65      ,  70.35833333,  56.5       ,  58.65      ,
        58.46625   ,  74.2975    ,  80.5375    ,  60.48125   ,
        83.3125    ,  71.7525    ,  90.57      ,  64.55875   ,
        75.52075   , 121.84270833,  60.14479167,  73.06875   ,
        72.50625   ,  95.4375    ,  83.33541667,  76.8125    ,
        94.34125   ,  82.03291667,  60.2375    ,  82.46666667,
        69.97125   ,  81.11666667,  83.87083333,  65.28166667,
        60.75166667,  65.4475    ,  65.359375  ,  84.4275    ,
        50.68      ,  64.69821429,  64.8625    ,  77.59166667,
        68.4265625 ,  53.299     ,  77.94375   ,  62.5025    ,
        73.44392361,  51.61      ,  68.12229167,  67.84375   ,
        65.55      ])

In [59]:
# score
score= model.score(X_test, y_test)
print('Score : ',score)

Score :  0.702169217741893


In [61]:
# evaluation through r2 score
from sklearn.metrics import r2_score
score1=r2_score(y_test,predictions)
print('R2 Score : ', score1)

R2 Score :  0.702169217741893


--------------